const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "+17723106853";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Mz Phantom",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Mz Phantom",

  sessionName:process.env.SESSION_ID || "SUHAIL_18_32_04_06_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQ4LFxuICAgICAgICA3OSxcbiAgICAgICAgNzQsXG4gICAgICAgIDI2LFxuICAgICAgICAyNDYsXG4gICAgICAgIDkzLFxuICAgICAgICAyNTEsXG4gICAgICAgIDUyLFxuICAgICAgICAxOTUsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxNzksXG4gICAgICAgIDQ4LFxuICAgICAgICAyOCxcbiAgICAgICAgMTY4LFxuICAgICAgICAyNTIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTEyLFxuICAgICAgICA2LFxuICAgICAgICA5MCxcbiAgICAgICAgMjQyLFxuICAgICAgICA1OSxcbiAgICAgICAgMTgsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTkyLFxuICAgICAgICA0MSxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMjcsXG4gICAgICAgIDE5MixcbiAgICAgICAgMjEyLFxuICAgICAgICAyMjcsXG4gICAgICAgIDExMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDksXG4gICAgICAgIDExNCxcbiAgICAgICAgMTYyLFxuICAgICAgICA4NCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMDYsXG4gICAgICAgIDIsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTkxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTg2LFxuICAgICAgICA3MSxcbiAgICAgICAgMTMyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDk2LFxuICAgICAgICA4MyxcbiAgICAgICAgNTMsXG4gICAgICAgIDE3LFxuICAgICAgICA2MCxcbiAgICAgICAgMTY2LFxuICAgICAgICA1MCxcbiAgICAgICAgNzgsXG4gICAgICAgIDg4LFxuICAgICAgICAxMzYsXG4gICAgICAgIDgwLFxuICAgICAgICAxMzksXG4gICAgICAgIDEwNSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTUwLFxuICAgICAgICA2NSxcbiAgICAgICAgMzJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE5MixcbiAgICAgICAgNDYsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTEwLFxuICAgICAgICAyMTUsXG4gICAgICAgIDc1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDUxLFxuICAgICAgICA3MixcbiAgICAgICAgMjUsXG4gICAgICAgIDE0NSxcbiAgICAgICAgNDYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTM3LFxuICAgICAgICA0LFxuICAgICAgICAxMjMsXG4gICAgICAgIDYyLFxuICAgICAgICAxNjAsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTE4LFxuICAgICAgICA1MixcbiAgICAgICAgMTQ4LFxuICAgICAgICAxMjgsXG4gICAgICAgIDI5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgNjYsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNDgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTI2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU3LFxuICAgICAgICA4NSxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNDMsXG4gICAgICAgIDM5LFxuICAgICAgICAyMDcsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjUwLFxuICAgICAgICAyMCxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNjEsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMzgsXG4gICAgICAgIDIwMixcbiAgICAgICAgNzcsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTc5LFxuICAgICAgICAxNzAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjQ1LFxuICAgICAgICA1MCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyNTEsXG4gICAgICAgIDc2LFxuICAgICAgICAyMTQsXG4gICAgICAgIDExMyxcbiAgICAgICAgMjQyLFxuICAgICAgICAxMjEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMzgsXG4gICAgICAgIDE4LFxuICAgICAgICA4NlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDUsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjYsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTcyLFxuICAgICAgICAxNDIsXG4gICAgICAgIDcwLFxuICAgICAgICA4MSxcbiAgICAgICAgMTIsXG4gICAgICAgIDM1LFxuICAgICAgICAxMTAsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTMzLFxuICAgICAgICAyMTAsXG4gICAgICAgIDI1MixcbiAgICAgICAgOCxcbiAgICAgICAgNTIsXG4gICAgICAgIDIwOSxcbiAgICAgICAgOTQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMzksXG4gICAgICAgIDkwLFxuICAgICAgICAxNDEsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjcsXG4gICAgICAgIDE0LFxuICAgICAgICA3NSxcbiAgICAgICAgMjExLFxuICAgICAgICA5LFxuICAgICAgICA2OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDksXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTE3LFxuICAgICAgICAyNDUsXG4gICAgICAgIDEyNSxcbiAgICAgICAgOSxcbiAgICAgICAgMTAsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjA5LFxuICAgICAgICA0OSxcbiAgICAgICAgMjMwLFxuICAgICAgICA5OSxcbiAgICAgICAgMTcwLFxuICAgICAgICA4NyxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEyNixcbiAgICAgICAgMjA3LFxuICAgICAgICA1MSxcbiAgICAgICAgMTI4LFxuICAgICAgICAyMjYsXG4gICAgICAgIDk1LFxuICAgICAgICAxNjMsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTg2LFxuICAgICAgICAxMDAsXG4gICAgICAgIDYxLFxuICAgICAgICAxNzYsXG4gICAgICAgIDEwOCxcbiAgICAgICAgOCxcbiAgICAgICAgODgsXG4gICAgICAgIDgwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMCxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMTE1XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIyLFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgOSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICA5NixcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICA4NSxcbiAgICAgICAgICA4NyxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAxNixcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxMDBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjcsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMzEsXG4gICAgICAgIDI0NixcbiAgICAgICAgNzgsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMjIsXG4gICAgICAgIDIyMixcbiAgICAgICAgMzksXG4gICAgICAgIDIwMixcbiAgICAgICAgMTUsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMCxcbiAgICAgICAgMTAyLFxuICAgICAgICA4OSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNTksXG4gICAgICAgIDQwLFxuICAgICAgICAyMCxcbiAgICAgICAgMTg4LFxuICAgICAgICAyMTksXG4gICAgICAgIDMsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTQwLFxuICAgICAgICAyNDEsXG4gICAgICAgIDgwLFxuICAgICAgICAxNDksXG4gICAgICAgIDEwNixcbiAgICAgICAgMTkwLFxuICAgICAgICA3LFxuICAgICAgICA4LFxuICAgICAgICAyMjYsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTMsXG4gICAgICAgIDQ0LFxuICAgICAgICAyNyxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMjMsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTg2LFxuICAgICAgICAyMDIsXG4gICAgICAgIDk1LFxuICAgICAgICA0OSxcbiAgICAgICAgMTYwLFxuICAgICAgICAxMjMsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTIwLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgNjgsXG4gICAgICAgIDIsXG4gICAgICAgIDYzLFxuICAgICAgICAyMDQsXG4gICAgICAgIDY1LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE2NSxcbiAgICAgICAgNzEsXG4gICAgICAgIDE2LFxuICAgICAgICAyNDIsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTcxLFxuICAgICAgICAxNzgsXG4gICAgICAgIDdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDI2LFxuICBcImFkdlNlY3JldEtleVwiOiBcInY5T3g1eU42Nk84QXpBaFFZdEM2UzNnSlZ2MFVnQWhpejI0L1kyOFdiUzA9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMzU4NDMxNzE2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIyRDdBQzBGODkyMDI1Rjc3MUQ2MDZDMDBDOUEzQzMyOFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NDM5NjQzNDVcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMzNTg0MzE3MTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjE0MEIyMUU0RThEOTJEQ0RBQTYwQjBENUNGMDBBODE0XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTc0Mzk2NDM0NVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogNjEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogNjEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJFS0ZVQ21FOVRGdTh3U2pRZ01Sa3J3XCIsXG4gIFwicGhvbmVJZFwiOiBcIjBkZmMzMThmLWRkZGUtNDBkNC1iOWE5LTZkMDdlNWU3YTEyM1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMjEsXG4gICAgICAxNjQsXG4gICAgICAyNDMsXG4gICAgICAyMDAsXG4gICAgICAzLFxuICAgICAgMjUyLFxuICAgICAgMTg4LFxuICAgICAgMjE2LFxuICAgICAgMTY2LFxuICAgICAgMjEzLFxuICAgICAgODAsXG4gICAgICA5OSxcbiAgICAgIDE5MSxcbiAgICAgIDI0OCxcbiAgICAgIDEwNixcbiAgICAgIDYwLFxuICAgICAgNixcbiAgICAgIDE5MSxcbiAgICAgIDI1MCxcbiAgICAgIDE2NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyNDksXG4gICAgICAxNTcsXG4gICAgICAxOTksXG4gICAgICA1OSxcbiAgICAgIDc3LFxuICAgICAgNjcsXG4gICAgICA4LFxuICAgICAgNTAsXG4gICAgICAxMDYsXG4gICAgICAyMTMsXG4gICAgICAyOCxcbiAgICAgIDg2LFxuICAgICAgNTUsXG4gICAgICAzOCxcbiAgICAgIDI1MCxcbiAgICAgIDk2LFxuICAgICAgMTM0LFxuICAgICAgMjIyLFxuICAgICAgMTA2LFxuICAgICAgNlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCI1QlY4Qjk1TlwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzMzU4NDMxNzE2OjVAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJQcml2V29ya1wiLFxuICAgIFwibGlkXCI6IFwiMTA4NDY5OTY5NTMwOTkzOjVAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSXpKcGJVREVMU1J5NzhHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJ2N0huY0lteERIVTY5NVNSaGVJa3pLQUFaTnQyL2loYWtSWnNwOUExR1U4PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIlJPbjRPMGFwYys3QndKRzNEMnFDTWpiUlBMeSswWi9PdG1QRXN2Z0k4RXhHMzd3N09zb1ZWRVR5YllHSVRJVmhYS29oVFQvYnh1c2VGd0hEZTRaTUNBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImcyWHdXQUdET2t2ZnlFZ3BOTUJRRUQrSkJEQkw5Nk5zUmZHellWMFdsQ1AyMG1tOUUveHpxZXlLTzBZa0lNT0poa2pJaGRzTDhhSjlFQ1k0MEtxNEJnPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzM1ODQzMTcxNjo1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgNzlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTc0Mzk2NDM0NCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQU1JRlwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTUlGLmpzb24iOiAie1wia2V5RGF0YVwiOlwiM2R1bTRLQ2hkeVBnRlA2Mm1lTlZZQVc1RWp1eFJ0WlZPcWhZdE8xZGhEVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo5MTcwNzA5ODgsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc0Mzk2NDM0NTUxMFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "Mz",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
